alias java8='export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)'
alias java7='export JAVA_HOME=$(/usr/libexec/java_home -v 1.7)'

# github commands
alias gst="git st"
alias gbr="git br"
alias gco="git co"
alias gci="git ci"
alias ga="git add"
alias gap="git add -p"
alias gd="git diff"
alias gr="git reset"
alias gpu="git push origin"
alias gpul="git pull origin"

if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
