alias java8='export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)'
alias java7='export JAVA_HOME=$(/usr/libexec/java_home -v 1.7)'

# unix commands
alias ls="ls -lhFG"
alias latr="ls -latr --color=auto"

# github commands
alias gst="git st"
alias gbr="git br"
alias gco="git co"
alias gci="git ci"
alias ga="git add"
alias gap="git add -p"
alias gd="git diff"
alias gr="git reset"
alias gpu="git push origin"
alias gpul="git pull origin"
alias gchi="git check-ignore"
alias glog="git log --graph --all --pretty=format:'%C(yellow)%h%Creset%C(red)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
