export BASH_CONF="bash_profile"

export GIT_PS1_SHOWCOLORHINTS=1
export PROMPT_COMMAND='__git_ps1 "\[\e[32;1m\]\w\[\e[0m\]" "\[\e[37;1m\] $ " '

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

alias java8='export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)'
alias java7='export JAVA_HOME=$(/usr/libexec/java_home -v 1.7)'

# unix commands
alias ls="ls -lhFG"

# github commands
alias gst="git st"
alias gbr="git br"
alias gco="git co"
alias gci="git ci"
alias ga="git add"
alias gap="git add -p"
alias gd="git diff"
alias gr="git reset"
alias gpu="git push origin"
alias gpul="git pull origin"
alias gchi="git check-ignore"
alias glog="git log --graph --all --pretty=format:'%C(yellow)%h%Creset%C(red)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# GO
export GOPATH=~/Sarah/GO_PROJECTS
export PATH=$PATH:$GOPATH/bin

# recursively create directories then cd into it
function mcd () {
  mkdir -p $1
  cd $1
}
# start FLA VM
function start_fla_vm() {
  cd ~/Sarah/Client/development_vagrant/
  ssh sjohnston@127.0.0.1 -p 2222 -i private_key
}

# source rapid_decision gems before running specs
function _load_gems() {
  export GEM_HOME=/home/sjohnston/pinkbox/rapid_decision/etc/localgems
  export GEM_PATH=$GEM_HOME
  export OLD_PATH=$PATH
  export PATH=$GEM_HOME/bin:$PATH
 }
